version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    command: poetry run python -m manage runserver 8000
  frontend:
    build:
      context: ./cartesi_frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: yarn run dev
