name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: your-dockerhub-username/backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: your-dockerhub-username/frontend:latest
