name: Docker Publish Django backend

on:
  push:
    branches:
      - main

jobs:
  build-and-push-django-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for changes, build and push to Docker hub
        run: |
          if git diff --quiet --exit-code HEAD^ HEAD ./backend; then
            echo "No changes in folder, skipping Docker build."
            exit 0
          else
            echo "Changes detected in folder, building Docker image."
            docker build -f ./backend/Dockerfile.dev -t ${{ secrets.DOCKER_USERNAME }}/django_cartesi_backend:latest ./django_cartesi_backend
            docker push ${{ secrets.DOCKER_USERNAME }}/django_cartesi_backend:latest
          fi
